# Generated by Django 2.0.6 on 2018-06-02 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_makanan', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Minuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_minuman', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('makanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesmodel.Makanan')),
            ],
        ),
    ]
